### ISSUE TITLE
Crash on open with invalid selected item

### ISSUE THREAD

**Issue by vektor330** [mrmarkfrench/country-select-js#10]
If I create a text field with value like "123", call `$('#myelement').countrySelect()`, the select will appear correctly, but opening the dropdown will crash on

> [Error] TypeError: undefined is not an object (evaluating 'element.offset().top')
>	_scrollTo (countrySelect.js, line 418)
>	_showDropdown (countrySelect.js, line 231)
>	(anonymous function) (countrySelect.js, line 209)
>	dispatch (jquery-1.10.2.min.js, line 2)
>	handle (jquery-1.10.2.min.js, line 2)

I propose to add the following to `_scrollTo()`

    if (!element || !element.offset()) {
      return;
    }

**Comment by mrmarkfrench** [comment]
Or, you know, don't call it with invalid input?

Kidding. This should definitely be fixed. Do you want to submit your suggested fix as a pull request, or just have me implement it?

**Comment by vektor330** [comment]
If it's the same to you, I'd rather you fix it - my experience with pull
requests is limited. Thanks!

**Comment by mrmarkfrench** [comment]
Sure, no problem. It's easy enough for me to do, it's just that if you submit it as a pull request, you get credit for the contribution to the project. Some people don't care about that, others live and die (or their careers do) on their ability to demonstrate that they have their hands in on a lot of projects.

**Comment by mrmarkfrench** [comment]
The commit just a minute ago resolves this issue. The minified version of the code is also updated, and I've pushed a new version (v1.0.7) to both Bower and NPM.
