### ISSUE TITLE
Automatically Update Input on Lose Focus

### ISSUE THREAD

**Issue by immortalcy** [mrmarkfrench/country-select-js#13]
The user is allowed to type on the input and a country is automatically selected from the left.
The form submit however takes into consideration the value on the input field. This gives wrong submission since for example:

1. A user types in "ger"
2. The Germany flag is automatically selected on the dropdown
3. The term "ger" is saved on the database

There are of course many alternatives to overcome this problem but it would be brilliant to have the input filled with the correct name of the country once the user leaves that input.

**Comment by mrmarkfrench** [comment]
If you have a proposed implementation for this feature, I'd be happy to see a pull request.

**Comment by mrmarkfrench** [comment]
The recent pull request has resolved this issue. Thanks to @ahartz1 for providing the fix.
