### ISSUE TITLE
selectCountry not working

### ISSUE THREAD

**Issue by yeganehaym** [mrmarkfrench/country-select-js#16]
Hi
thaks for your code
$("#country").countrySelect("selectCountry", "US");
not working
give me error
type error : b is null

**Comment by mrmarkfrench** [comment]
Did it give you a line number or anything to go with that? Were you using the regular version of the JS file, or the minified one?

**Comment by yeganehaym** [comment]
hi sir
i am using min js but i changed it for line number
line number : 386
and i thank you again for your component , it is awesome thing
simple and useful

**Comment by mrmarkfrench** [comment]
Can you try it and see if the problem still happens with the non-minified version of the JS?

Also, any additional information you could provide would be helpful. What country was selected at the time you made the call? Did you make the call directly from your own code, or was it triggered by a particular event?

**Comment by yeganehaym** [comment]
yes i tested
i am using jquery in .net mvc but i tested by $("#txtCountry").countrySelect("selectCountry", "US"); too and i got error again

this is my code
 var country = $(this).data("iso2");
var txtcountry = $("#txtCountry").countrySelect("selectCountry", country);

however i fixed my problem with this for now
   var country = $(this).data("country");
var index = country.indexOf("(");
        if (index >= 0)
            country = country.substring(0, index);
   var txtcountry = $("#txtCountry").countrySelect("setCountry", country);
however iso2 is better for communication between jquery and database because country name can be diff with your selector and my db

**Comment by mrmarkfrench** [comment]
Can you try it with a lower-case country code? The country codes are all lower case in the data set. That might well fix your issue. If it does, I will make sure we handle both upper and lower case codes, but I want to confirm that we understand what caused the problem before I make any changes to the code.

**Comment by yeganehaym** [comment]
thanks
it worked with lowercase
i didn't to attention to it
thank you very much

**Comment by mrmarkfrench** [comment]
Alright, at least we know what the problem was. I will update the code to be able to handle mixed case country codes. I'll expect to get that updated tomorrow.

**Comment by mrmarkfrench** [comment]
Version 1.0.9 now corrects this issue, and allows both upper and lower case country codes to be used when calling selectCountry().
