### ISSUE TITLE
dial code instead of iso2 code?

### ISSUE THREAD

**Issue by yadhu** [mrmarkfrench/country-select-js#18]
How can I show dialcode instead of iso2 code in the extra input field?

**Comment by mrmarkfrench** [comment]
The plugin doesn't have a list of dial codes, it uses country codes. If you're interested in dialing codes, please take a look at the International Telephone Input plug-in, upon which this one is based ((https://github.com/Bluefieldscom/intl-tel-input.git). It will take care all of your international telephone handling needs.

**Comment by yadhu** [comment]
Thank you
