### ISSUE TITLE
The dropdown won't display fully for me

### ISSUE THREAD

**Issue by maxpen** [mrmarkfrench/country-select-js#20]
What could be causing that?

**Comment by mrmarkfrench** [comment]
Closing this issue, as I never got enough info to track this down. If you are having this issue, please let me know what browser and jQuery version you are using, and if the issue occurs in the `demo.html` page, or only on your own page. If it's only on your own page, the issue might be CSS conflicts on your page. You might also try enabling the `responsiveDropdown` option, which may resolve issues with the display size.
