### ISSUE TITLE
defaultCountry bug

### ISSUE THREAD

**Issue by VerzatileTom** [mrmarkfrench/country-select-js#28]
I have two dropdowns for countrySelect and I set the `defaultCountry` to 'ph' but only the first dropdown implemented the default. I used their class as a selector on instantiating countrySelect. any idea on this?

**Comment by Ghoughpteighbteau** [comment]
@VerzatileTom 

if it's like https://github.com/jackocnr/intl-tel-input then it's ignoring the value and picking the first one from the preferred country list.

**Comment by mrmarkfrench** [comment]
A previous update resolved this issue, which was caused by a bug in how the flag was updated when a default country was selected by setting the desired country code in the initialization options. This issue no longer occurs in the most recent update to the plugin.
