### ISSUE TITLE
Citizenship support

### ISSUE THREAD

**Issue by 4bdulll4** [mrmarkfrench/country-select-js#29]
I would highly recommend you to  add citizenship countries as an improvement  for this plugin. 

Thank you

**Comment by mrmarkfrench** [comment]
What do you mean by "citizenship countries"?

**Comment by 4bdulll4** [comment]
I mean Nationalities. for example, American, German, Turkish, Irish,... etc.

**Comment by mrmarkfrench** [comment]
So for example, the British Virgin Islands would say "UK"?
Or are you looking for the name of the nationality? So for United States of America, it would say "American"?

**Comment by 4bdulll4** [comment]
I am looking for the nationality. just like your second example.

**Comment by mrmarkfrench** [comment]
That's not really what the plugin is designed to do. If you need to use it for that purpose, I'd suggest changing the label. So instead of asking "What is your nationality?", use "What country are you from?" or "I am a citizen of" followed by the drop-down.
