### ISSUE TITLE
Initialization with a filled field containing parenthesis fails

### ISSUE THREAD

**Issue by zorbalaras** [mrmarkfrench/country-select-js#3]
Line 332: the value is retrieved as-is. It may contains () such as : "Greece (Ελλαδα)". Theses parenthesis seems to be interpreted as special characters in the RegExp and this country name does never match with the existing entry.
Just replaced line 332 with : var value = this.countryInput.val().replace(/(?=[() ])/g, '\\'); found here : http://stackoverflow.com/questions/22872974/javascript-regex-to-escape-parentheses-and-spaces

I'am not sure if the space escaping is really necessary, thought...

**Comment by mrmarkfrench** [comment]
I'm pretty sure that needed to be:
.replace(/(?=[() ])/g, '\\');

Note the double backslash in the replacement string, rather than a single. Otherwise it escapes the closing quote and causes all kinds of havoc.
