### ISSUE TITLE
On blur country and country_code inputs can be out of sync

### ISSUE THREAD

**Issue by limpakos** [mrmarkfrench/country-select-js#36]
You update the country val on blur based on the flag, but I think you should also update the country_code hidden input then. Otherwise, if you type something wrong and then blur, the name will be "fixed" but the code will remain empty... Hope all this makes sense...

Cheers!

**Comment by mrmarkfrench** [comment]
This issue was resolved by an earlier pull request, which now does a better job of ensuring that all of the elements (flag, country name, country code) are properly updated whenever one of them is selected, via blur, keyup, programatic change, or flag selection.
