### ISSUE TITLE
Npm or/and bower

### ISSUE THREAD

**Issue by skrobek** [mrmarkfrench/country-select-js#4]
Hey,

nice work. Did you consider to create package for bower and npm ?

**Comment by mrmarkfrench** [comment]
I've just published a Bower package (country-select-js), which Bower reports is matched against this GitHub repository. Looks like there's some indexing delay, however, as the package appears in the command-line search but is not yet discoverable on Bower page's package search.

**Comment by mrmarkfrench** [comment]
The NPM package is now also live, and is discoverable. I hadn't meant to close the issue until this was done, too, but I'll re-open it and then close again.

**Comment by skrobek** [comment]
@mrmarkfrench Thanks https://www.npmjs.com/package/country-select-js
