### ISSUE TITLE
UK flag is not right.

### ISSUE THREAD

**Issue by Skura23** [mrmarkfrench/country-select-js#45]
UK flag is not right. UK flag and its country name doesn't match.

**Comment by mrmarkfrench** [comment]
Issue #15 referenced a difference between the flag images used for the original plugin this one is based on, and the ones used here (the ones here hadn't been updated when the other plugin updated their images).

Now that this issue is resolved, do you see the correct flag?

**Comment by mrmarkfrench** [comment]
If you still see the wrong flag, can you post a screenshot of what you see?

**Comment by mrmarkfrench** [comment]
Given that it's been more than six months without another report of this issue, and no feedback here. I am closing this issue. If you are still seeing the problem with the updated version of the plugin, please let me know.
