### ISSUE TITLE
Setting new country data didn't effect

### ISSUE THREAD

**Issue by MAZEN-Kenjrawi** [mrmarkfrench/country-select-js#46]
I tried to customize countries data as I need multi languages in my website so I need to translate countries' names.
What I did is:
`var countrySelect = $(" .country_selector").countrySelect({
    defaultCountry: "tr",
    preferredCountries: ['tr', 'fr', 'ro', 'sp', 'sa', 'eg']
});
var countries = [];
$.getJSON('countries.json', function(results){
	$.each(results, function(index, country){
		countries.push({name: country.n, iso2: country.i});
	});
	$.fn.countrySelect.setCountryData(countries);
}).fail( function(d, textStatus, error) {
	console.error("getJSON failed, status: " + textStatus + ", error: "+error)
});`
Nothing happened and if I `console.log(allCountries)` where the `setCountryData` is defined it shows my new list but the front-end didn't apply it.

**Comment by digz6666** [comment]
How about destroying the current object and re initialize again?

**Comment by MAZEN-Kenjrawi** [comment]
Could you be more specific, please? How could I do that?

**Comment by MAZEN-Kenjrawi** [comment]
Could you be more specific, please? How can I do that?
The documentation says: 
> setCountryData
> Set all of the plugin's country data.
> `$.fn.countrySelect.setCountryData(countryData);`

You mean that I should remove my selector tag, and then add it with the new options, and reconstruct the object?

**Comment by digz6666** [comment]
@MAZEN-Kenjrawi if you read the documentation, there's a method to destroy the current country select.
Also you have to clean the value of the select, or it will throw:
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

```javascript
$(".country_selector").countrySelect("destroy");
$(".country_selector").val('');
$("#depositCountry").countrySelect({
...
});
```

**Comment by mrmarkfrench** [comment]
I am closing this issue, as I'm reasonably confident that @digz6666 has provided a working solution to be able to overwrite the country data to display as @MAZEN-Kenjrawi needs.
