### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by QuDDoSS** [mrmarkfrench/country-select-js#50]
**Uncaught TypeError: Cannot read property 'toLowerCase' of undefined**

This error appear when i close tab , and re-open with ( CTRL+SHIFT+T) or when I submited form and get back for edit . This error is present in demo file too.

**Comment by digz6666** [comment]
it happens when you call destroy too,

**Comment by digz6666** [comment]
Call $("#country").val('') before making any calls.

**Comment by sirdik** [comment]
Calling $("#country").val('') is not possible solution. It is clearing loaded values previosly saved.

**Comment by Aaronfischer** [comment]
I am also experiencing this. Anyone have an fixes?

**Comment by hkellock** [comment]
I just installed country-select-js npm package version 2.0.1. The fix mentioned [above](https://github.com/mrmarkfrench/country-select-js/commit/987a79cee306aca2051431e79c1c3fe5b77e4fc0) appears in the function `_initAutoCountry` in the source code:
/country-select-js/src/js/countrySelect.js
However, the fix does not appear in the build folder files:
/country-select-js/build/js/countrySelect.js
/country-select-js/build/js/countrySelect.min.js

**Comment by mrmarkfrench** [comment]
The pull request which merged the missing fix into the `build` directory from `src` has now been merged, and this issue should be resolved. Thanks to @qhieu45 for resolving this issue.

**Comment by mapreal19** [comment]
@mrmarkfrench I guess this should have been deployed with a new version? I had to target master branch in my `package.json`
