### ISSUE TITLE
"responsiveDropdown" parameter has no effect

### ISSUE THREAD

**Issue by alexherbs** [mrmarkfrench/country-select-js#57]
Hi there,

I found out that your written parameter "responsiveDropdown" doesn't work at all. It doesn't work because it doesn't even exists in the javascript files or somewhere. I exactly need your plugin with the behaviour you have written in your Readme and it would be great if you could add that feature.

Thanks, Alex

**Comment by escanxr** [comment]
Hi @alexherbs , it's an old issue but I just added this option if you still need it!

**Comment by mrmarkfrench** [comment]
Given that I've seen no further activity on this issue, and that @escanxr 's pull request resolved the issue, I'm going to close this out.
