### ISSUE TITLE
Styling the dropdown

### ISSUE THREAD

**Issue by Mike-Van** [mrmarkfrench/country-select-js#62]
can anyone tell me how to customize the flags dropdown like selected flag size, dropdown button and sth else? Suppose i want it to look like this
![untitled](https://user-images.githubusercontent.com/29220303/47415435-a1408e80-d79d-11e8-8df0-8c604e771039.png)

**Comment by mrmarkfrench** [comment]
The flags are all taken from a single image, so you could scale them, but they're low enough resolution I'm not sure you're going to be happy with the results.

You can also add your own styles to the `.country-select-input` class (this is the container the drop-down will be built inside of). These will allow you to set various styling values for the elements the plugin creates inside of that container. I'd recommend just inspecting the built elements to see what you might like to adjust.
