### ISSUE TITLE
Initialize countrySelect on new elements added in a ajax request is not existing

### ISSUE THREAD

**Issue by fede72bari** [mrmarkfrench/country-select-js#68]
I am experiencing that I cannot find the function .countrySelect in new elements added within an ajax request since the function really does not exist in new #countryN input tags. I thought it was a problem of scope, after exhausting attempts, at least for a beginner like me, I found that probably there is an event linked to the page load or ready so that just at the first-page load the whole countrySelect.js script attach the plugin function to many page elements including input tags. So my question is how can i get the same for the new elements that are added basically after clicking a SHOW MORE button? Is there a way to recall the function inside the countrySelect.js script that attaches the plugin countrySelect function? Or a way to trigger the event load/ready page? Thanks.

**Comment by mrmarkfrench** [comment]
So I just tried this and it's working as expected for me.

Here's my dead-simple example. I took the `demo.html` file from the plugin and added the following to the end:

`<script>
	// Make sure we don't run this until after everything else has been loaded.
	// Using the document click handler ensures that everything else is setup first,
	// which ensures we're not cheating and adding our new element before the
	// plugin attaches to form elements the first time.
	$(document).on('click', function(){
		// Step 1: Create a new element from a simulated AJAX request
		var newInput = $('<input type="text" id="country_selector_ajax" name="country_selector_ajax">');
		// Step 2: Add the new element to the page
		$('form').append(newInput);
		// Step 3: Run the plugin on the new element
		$(newInput).countrySelect({ defaultCountry: 'au' });
		// Step 4: Profit!
	});
</script>`

This will add a new selector every time you click on the page, and they all get a handler added to them with a drop-down menu of flags.

**Comment by fede72bari** [comment]
Dear Mark,

thank you so much for your reply. I have repeated your test also in the
context of ajax call and keeping it simple; in this way i have to say that
works it here too. But still, I have that trouble in the page I need to
complete and I am driving crazy because the php function that adds new
elements is the same that create the first ten as well as the js functions
and event that manage the new ones are the same used for the first ones. So
no reason for this difference of behavior apparently. Giving a look to the
input objects on which I apply countrySelect and logging them in the
console here in the attached image there are the two differences, on the
left side one of the first 10 elements in main page response, on the right
one of the elements added through ajax call. If you have any idea please
tell me I cannot see anymore workaround to understand the origin of the
problem and have been close at home for covid-19 for 5 weeks ... i don't
have any more walls on which beat my head! :-) www.pharmacomparison.com -->
search by "aspirin" --> scroll down, "show more".

Thanks.

f

The working attemps:

*controller:*














*    function countrySelectTest(){
$this->load->view('countrySelectTest');            }        function
countrySelectTestresult(){                $random = mt_rand(0,999999999);
      $res['html_text']  = '<input type="text"
id="country_selector_ajax'.$random.'" name="country_selector_ajax">';
  $res['state']  = 'success';        $res['random'] = $random;
  echo json_encode($res);    }*

*viewer*



















































































































*<!DOCTYPE html><html> <head> <meta charset="utf-8"> <title>Country Select
JS</title> <link rel="stylesheet" href="build/css/countrySelect.css"> <link
rel="stylesheet" href="build/css/demo.css">                <link
rel="stylesheet" href="<?php echo base_url('assets/css/countrySelect.css');
?>">            <link rel="stylesheet" href="<?php echo
base_url('assets/css/demo.css'); ?>">                  <script
type="text/javascript" src="<?php echo base_url();
?>assets/js/jquery.js"></script>        <script type="text/javascript"
src="<?php echo base_url('assets/js/countrySelect.min.js'); ?>"></script>
  </head> <body> <h1>Country Select JS</h1> <form> <div class=""
id="country"> <input id="country" type="text"> <label
for="country_selector" style="display:none;">Select a country
here...</label> </div> <button type="submit"
style="display:none;">Submit</button> </form>            <button
type="submit"  id="local_test">Local Test</button>            <button
type="submit"  id="ajax_test">Ajax Test</button>  <script> $("#country").countrySelect({ //
defaultCountry: "jp", // onlyCountries: ['us', 'gb', 'ch', 'ca', 'do'], //
responsiveDropdown: true, preferredCountries: ['ca', 'gb', 'us'] });
</script><script> // Make sure we don't run this until after everything
else has been loaded. // Using the document click handler ensures that
everything else is setup first, // which ensures we're not cheating and
adding our new element before the // plugin attaches to form elements the
first time. $('#local_test').on('click', function(){ // Step 1: Create a
new element from a simulated AJAX request     var newInput = $('<input
type="text" id="country_selector_local" name="country_selector_local">');
// Step 2: Add the new element to the page $('form').append(newInput); //
Step 3: Run the plugin on the new element
$('#country_selector_local').countrySelect({ defaultCountry: 'au' }); //
Step 4: Profit! }); $('#ajax_test').on('click', function(){
//the URL return te same content of previous newInput            $.ajax({

    url:
'https://www.pharmacomparison.com/frontController/countrySelectTestResult/
<https://www.pharmacomparison.com/frontController/countrySelectTestResult/>',
                 type: "POST",
                             enctype: 'multipart/form-data',
                                       data: {
                                                   product_info_id: 'test'

      },                  method: 'Post',                   dataType:
'json',                                  success: function(response) {
                  if(response.state=='error'){
            alert(response.msg);                       }
                          if(response.state=='success'){
                             // Step 2: Add the new element to the page
                    $('form').append(response.html_text);
      // Step 3: Run the plugin on the new element
$('#country_selector_ajax'+response['random']).countrySelect({
defaultCountry: 'au' });                         // Step 4: Profit!
              }                },                error: function(xhr,
status, error) {
 console.log(xhr);console.log(status);console.log(error);
  alert("The request returned an error, please alert the site
administrators (" + status +").");                }                 });
         }); </script> </body></html>*



Il giorno dom 12 apr 2020 alle ore 08:19 Mark French <
notifications@github.com> ha scritto:
