### ISSUE TITLE
Unable to change width of input field

### ISSUE THREAD

**Issue by candemah** [mrmarkfrench/country-select-js#69]
I am trying to use the country-select plug in on a bootstrap form.  Everything is working fine except for the fact that I can't change the size of the input element.  I have tried to set the width of the element to 100% as well as the div the element is inside of, however the size of the input element stays the same.

I'm sure it's a simple issue that I'm missing....

My very simple code is below:
css:
.country-select-input{
    border-style:solid;
    width:100%;
}

html:
<div class="form-row">
   <div class="col-8">
      <div class="form-row">
         <label for="country">Country</label>
      </div>
      <div class="form-row">
         <div class="country-select-input">
            <input id="country" type="text" class="form-control">
         </div>
      </div>            
      <input id="country_code" type="hidden" class="form-control">
  </div>
</div>

and js:
$("#country").countrySelect({
   defaultCountry:"au"
 })

**Comment by mrmarkfrench** [comment]
The issue is going to be that the `.country-select` class is on a `div` element that is wrapped around the input. You will need to adjust the width of both.

So  you will need to set the width of the `.country-select` class to 100% (just like you've done in your example), but then also set the width of your input element. So, in your example, add the following to your stylesheet:
`#country {
width: 100%
}`

**Comment by candemah** [comment]
@mrmarkfrench thanks.  It didn't fix the problem, however I discovered that if I put a px width rather than 100% it adjusted the size.  I'm guessing based on that finding there must be something earlier in my code that is causing the issue

**Comment by mrmarkfrench** [comment]
@candemah interesting. I guess I should also note that setting the width of any element (including the input and the `div` the plugin wraps it in) to 100% makes it take up the full width of it's parent element. IF the bootstrap `form` or any other containing element has a fixed width set, it won't allow your input to get any wider than that using 100%.

From what you say it sounds like there's some other style rule or containing element that's limiting the width of your country select input. Good luck tracking that down!
