### ISSUE TITLE
Need trigger when update countryCode (hidden field)

### ISSUE THREAD

**Issue by NamPNQ** [mrmarkfrench/country-select-js#7]
Look:
https://github.com/mrmarkfrench/country-select-js/blob/master/build/js/countrySelect.js#L430
https://github.com/mrmarkfrench/country-select-js/blob/master/build/js/countrySelect.js#L354

Hidden field not auto trigger when change value
We need trigger event change in here

**Comment by mrmarkfrench** [comment]
If you have a specific solution in mind, I'd be happy to accept a pull request.

**Comment by mrmarkfrench** [comment]
Thanks for your contribution! The version has been incremented to 1.0.6 to reflect this fix, and new Bower and NPM package files pushed to match the new tag.
