### ISSUE TITLE
Full width input not working

### ISSUE THREAD

**Issue by rajdnp** [mrmarkfrench/country-select-js#75]
I am trying to add full width 100% as you have mentioned in docs but it's not increasing the width.

**Comment by mrmarkfrench** [comment]
Can you share an example? Most problems of this type are because the input is set to 100% width but the container DIV is narrower, so the input fills the container but does not span the display.

**Comment by rajdnp** [comment]
@mrmarkfrench 
## I am using bootstrap 4 and here is my form input control
```
<div class="col-sm-6">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="select" name="country" id="country" >

                </div>
            </div>
```

## JS

```
 $("#country").countrySelect({

        });
```
## Result

![image](https://user-images.githubusercontent.com/61657297/97936167-b7c44c00-1da0-11eb-9a0f-f9bb9bc025d5.png)

## ISSUE: I want to get the country input width also as same the above input field. i tried a lot in "countrySelect.css" file and i have done many changes in the css but nothing getting worked out. please help me..

**Comment by mrmarkfrench** [comment]
I can't be sure without seeing an example (as compared to a screenshot of one), but I'm pretty sure that the outer div (with the Bootstrap class of col-sm-6) is not full width. As a result, the input is set to full width, but it only expands to fill the container div, which is set to a smaller width by Bootstrap.

What happens if you change the class of the outer div to be just "col"?

**Comment by mrmarkfrench** [comment]
I haven't seen any further activity on this issue in more than a month. I'm going to assume you've got it working, as it is definitely working as expected for other users. I'm going to close this issue. If you are still having the problem, please share some additional information (an example on JSFiddle would be great) and we'll see what we can do for you.

**Comment by rajdnp** [comment]
Hai Mark, The issue is fixed i have gone through the docs and fixed the
issue by implementing this.

[image: image.png]
Thanks for your support. :)
