### ISSUE TITLE
How to get the selected country data after it is selected from the list?

### ISSUE THREAD

**Issue by ohlogic** [mrmarkfrench/country-select-js#80]
I am trying to get the country name and its country two character code after a selection from the country flag list.

For now, I am using this code below because the selected data isn't available until after a country selection is made.  Is there a better way to get the country data after a selection is done?

    $('.country').click(function(e) {{
    
        setTimeout(function() {{
            alert(  $("#country_selector").countrySelect("getSelectedCountryData")['name'] + ' ' + 
            $("#country_selector").countrySelect("getSelectedCountryData")['iso2']  );
        }}, 2000);
     
    }});

**Comment by mrmarkfrench** [comment]
If you have a field for the plugin to set the country code, you could just use an on-change event for that field. The field will contain the 2-character code, and will be updated any time the user makes a new selection. That way there's no need for a wait on a timeout function, and you can grab the code directly, you'd only need to look to the other field for the country name.

**Comment by mrmarkfrench** [comment]
For a little more clarity, here's a code example:
`$('#country_selector_code').change(function(e) {{ 
    alert( $("#country_selector").countrySelect("getSelectedCountryData")['name'] + ' ' + $("#country_selector_code").value );
}});`

**Comment by ohlogic** [comment]
That was it, the jquery change function works great to select the country.  Thanks.

**Comment by mrmarkfrench** [comment]
Great, glad to hear you've got it working. I'm going to close out this issue, then.
