### ISSUE TITLE
Latest version on npmjs

### ISSUE THREAD

**Issue by koukouchris** [mrmarkfrench/country-select-js#88]
Just wanted to check if the latest version (2.0.3) will be also available in npm? (https://www.npmjs.com/package/country-select-js?activeTab=versions) I have an issue that is fixed i would love to update plugin through npm. Thanks!

**Comment by mrmarkfrench** [comment]
NPM was updated a few moments ago, and the latest version (v2.1.0) is now available for package install through NPM.
